name: CD

on:
  push:
    tags:
      - 'release/*'

jobs:
  run-build:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    needs: run-build
    steps:
      - uses: actions/checkout@v3

      - name: Version Check
        run: ci/check-version.sh

      - name: Download artifact
        run:
          ci/gh-fetch-artifacts.sh $GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: out/*

