name: CI

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup buildx backend for docker
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: merge-tool-agent:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Build
      run: docker run -v ${{ github.workspace }}:/workspace merge-tool-agent ci/build-ci.sh

    - name: Run Test
      run: docker run -v ${{ github.workspace }}:/workspace merge-tool-agent ci/test-ci.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: merge_tool
        path: |
          out/merge_tool
          out/merge_tool.exe
          
